# **Numpy** (ndarrry)

- ndarray 타입의 데이터만 다룬다
- 내부 원소는 동일한 dtype으로만 저장




In [1]:
import numpy as np

In [3]:
##array() 함수 : 다양한 인자를 입력받아 ndarray로 변환
##np.array()는 하나의 인자만 받음
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape) ##shape속성 -> 행, 열의 수 -> 차원의 수

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)


array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [4]:
##ndarray.ndim 속으로 차원 알기

print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim)) ##format안에서 몇번째 가져올지

array1: 1차원, array2: 2차원, array3: 2차원


In [5]:
##ndarray의 데이터 타입 -> dtype 속성

list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
##데이터 타입이 섞였으면?

list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np. array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
##astrype('') 데이터 타입 변경

#int ndarray 생성-> float64
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

#float -> int32
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

#float 생성 -> int32
array_float1 = np.array([1.1, 2.1, 3.1])
array_int1 = array_float1.astype('int32')
print(array_int1, array_int1.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [9]:
##andarray 편하게 생성
#np.arange()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

#zeros(), ones() -> dtype 디폴트 float64
zeroe_array = np.zeros((3,2), dtype = 'int32')
print(zeroe_array)
print(zeroe_array.dtype, zeroe_array.shape)

ones_array = np.ones((3,2))
print(ones_array)
print(ones_array.dtype, ones_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
#reshape
# 0〜9까지의 1차원 ndarray를 2로우x5칼럼과 5로우x2칼럼 형태로 2차원 ndarray로 변환

array1 = np.arange(10)
print('array1:\n', array1)
array2 = array1.reshape(2,5)
print('array2:\n', array2)
array3 = array1.reshape(5,2)
print('array3:\n', array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1.reshape(3,4) ##수가 맞아야 함

ValueError: cannot reshape array of size 10 into shape (3,4)

In [12]:
# reshape()에  -1값을 인자로 적용한 경우에 어떻게 ndarray의 size를 변경?

array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape (2, 5)
array3 shape (5, 2)


In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4) ## 수가 맞아야 함

ValueError: cannot reshape array of size 10 into shape (4)

In [18]:
## reshape(-1,1)을 이용해 3차원을 2차원으로, 1차원을 2차원으로 변경

array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print(array3d.tolist())

#3차원 -> 2차원
array2d = array3d.reshape(-1,1)
print(array2d.tolist())
print("크기는 ", array2d.shape)

#1차원 -> 2차원
array2d_1 = array1.reshape(-1,1)
print(array2d_1.tolist())
print("크기는 ", array2d_1.shape)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
크기는  (8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]]
크기는  (8, 1)


In [21]:
# 1부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(10)
print('array1: ', array1)
#index는 0부터 시작
value = array1[2]
print('value: ', value)
print(type(value))
#맨뒤의 값
print('맨뒤의 값: ', array1[-1], ', 뒤에서 두번째 값: ', array1[-2])

array1:  [0 1 2 3 4 5 6 7 8 9]
value:  2
<class 'numpy.int64'>
맨뒤의 값:  9 , 뒤에서 두번째 값:  8


In [25]:
#데이터 수정
array1[0] = 9
array1[8] = 0
print("수정된 데이터는 ", array1)

#1차원 ndarray를 2차원의 3 x3 ndarray로 변환한 후 [row, col]을 이용해 2차원 ndarray에서 데이터를 추출
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, -1)
print("차원 수정된 데이터는 ", array2d)

print('(row=0, col =0) index 가르키는 값:, ', array2d[0, 0])
print('(row=0, col =1) index 가르키는 값:, ', array2d[0, 1])
print('(row=1, col =0) index 가르키는 값:, ', array2d[1, 0])
print('(row=2, col =2) index 가르키는 값:, ', array2d[2, 2])

수정된 데이터는  [9 1 2 3 4 5 6 7 0 9]
차원 수정된 데이터는  [[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col =0) index 가르키는 값:,  1
(row=0, col =1) index 가르키는 값:,  2
(row=1, col =0) index 가르키는 값:,  4
(row=2, col =2) index 가르키는 값:,  9


In [26]:
#슬라이싱으로 ndarray 추출

array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [27]:
array1 = np.arange(1, 10)
array4 = array1[:3] #처음부터 index 3까지
print(array4)

array5 = array1[3:] #index 3부터 끝까지
print(array5)

array6 = array1[:] #전부
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [32]:
# 2차원 ndarray에서 슬라이싱
# 1차원 1~9 -> (3,3)
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print("array2d: \n", array2d)

print("array2d[0:2, 0:2]\n", array2d[0:2, 0:2])
print("array2d[1:3, 0:3]\n", array2d[1:3, 0:3])
print("array2d[1:3, :]\n", array2d[1:3,:])
print("array2d[:, :]\n", array2d[:, :])
print("array2d[:2, :1]\n", array2d[:2, :1])
print("array2d[:2, :0]\n", array2d[:2, 0])


array2d: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, :1]
 [[1]
 [4]]
array2d[:2, :0]
 [1 4]


In [38]:
#row(0, 1)축 1차원만 반환하기

print(array2d[0])
print(array2d[1]) ##print()안하면 마지막 줄만 반환

[1 2 3]
[4 5 6]


In [40]:
#팬시 인덱싱
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0,1], 2]
print(array3.tolist())

array4 = array2d[[0,1], 0:2]
print(array4.tolist())

array5 = array2d[[0, 1]]
print(array5.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [42]:
#불린 인덱싱

#값이 5보다 큰 것만
array1d = np.arange(1, 10)
array3 = array1d[array1 > 5]
#결과값
print("array1d>5 결과값: ", array3)
# ndarray > 5 라는 불린 식의 반환값은?
print(array1d > 5)

array1d>5 결과값:  [6 7 8 9]
[False False False False False  True  True  True  True]


In [44]:
#T, F로 인자를 받아서 위와 같은 영역의 값들 출력

boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
print(boolean_indexes)

#T/F 데이터 값의 array가 인자로 들어가는 순간
#T들의 위치가 차례대로 기입할 index가 됨
array3 = array1d[boolean_indexes]
print(array3)

array4 = array1d[[5, 6, 7, 8]] #팬시 인덱스
print(array4)

[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]


In [47]:
#정렬하자
#sort()의 두가지 방식

#넘파이에서 sort() 호출
org_array = np.array([1, 9, 8, 2])
print("원본 행렬: ", org_array)

sort_array1 = np.sort(org_array)
print("넘파이 sort() 호출 후 반환된 행렬 ", sort_array1)
print("원본 행렬: ", org_array)

#ndarray에서 sort() 호출
sort_array2 = org_array.sort()
print(".sort() 호출 후 반환된 행렬: ", sort_array2)
print("원본 행렬 ", org_array)


원본 행렬:  [1 9 8 2]
넘파이 sort() 호출 후 반환된 행렬  [1 2 8 9]
원본 행렬:  [1 9 8 2]
.sort() 호출 후 반환된 행렬:  None
원본 행렬  [1 2 8 9]


In [48]:
#내림차순으로 정렬
sort_array1_desc = np.sort(org_array[::-1])
print("내림차순으로 정렬: ", sort_array1_desc)

내림차순으로 정렬:  [1 2 8 9]


In [50]:
#2차원
array2d = np.array([[8,12], [7,1 ]])

#로우 방향으로 정렬
sort_array2d_axis0 = np.sort(array2d, axis=0)
print("로우 방향으로 정렬:\n", sort_array2d_axis0)

#칼럼 방향으로 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print("칼럼 방향으로 정렬:\n", sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [51]:
#정렬된 행렬의 인덱스 반환하기
#np.argsort()
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)


<class 'numpy.ndarray'>
[1 0 3 2]


In [52]:
#내림차순 정렬시 인덱스 반환하기
org_array = np.array([3, 1, 9, 5])
sort_indices_decs = np.argsort(org_array)[::-1]
print(sort_indices_decs)

[2 3 0 1]


In [53]:
#이름 & 성적

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

#성적 순으로 정렬된 이름
sort_indices_asc = np.argsort(score_array)
print("성적 오름차순 시 score_array의 인덱스: ", sort_indices_asc)
print("성적 오름차순으로 이름 출력: ", name_array[sort_indices_asc])

성적 오름차순 시 score_array의 인덱스:  [0 2 4 1 3]
성적 오름차순으로 이름 출력:  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [54]:
#선형대수 연산

A = np.array([[1, 2, 3], [4, 5, 6]])
B  = np.array([[7, 8], [9, 10], [11, 12]])

#행렬 곱 np.dot()
dot_product = np.dot(A, B)
print("곱셉:\n", dot_product)

#전치 행렬 np.transpose()

transpose_mat = np.transpose(A)
print("전치:\n", transpose_mat)

곱셉:
 [[ 58  64]
 [139 154]]
전치:
 [[1 4]
 [2 5]
 [3 6]]


# **판다스**
- DataFrame이 주요 객체
- index와 DataFrame의 요소인 Series를 잘 다루는 것 중요

In [63]:
from google.colab import files
uploaded = files.upload()



Saving train.csv to train.csv


In [68]:
import pandas as pd
titanic_df = pd.read_csv("train.csv")
print('titanic 변수 type：', type(titanic_df))
titanic_df.head(3)


titanic 변수 type： <class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [70]:
print('DataFrame 크기: ', titanic_df.shape)

DataFrame 크기:  (891, 12)


In [71]:
#info() Null 개수, 데이터 타입, 전체 데이터 건수
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [72]:
#describe() 데이터 분포도
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [75]:
#values_counts: 칼럼값의 유형, 데이터타입과, 개수
values_counts = titanic_df['Pclass'].value_counts()
print(values_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [77]:
#Series란?
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))
titanic_pclass.head()

<class 'pandas.core.series.Series'>


0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [80]:
#Pclass 값의 건수 -> Series
values_counts = titanic_df['Pclass'].value_counts()
print(type(values_counts))
print(values_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [83]:
#vlue_counts() 파라미터 dropna = False Null도 알고 싶어

print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')

print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna = False))


titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64


In [87]:
import numpy as np

col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape：', array1.shape)
#리스트 -> DataFrame
df_list1=pd.DataFrame(list1, columns=col_name1)
print(df_list1)
#넘파이 ndarray -> DataFrame
df_array1=pd.DataFrame(array1, columns=col_name1)
print(df_array1)

array1 shape： (3,)
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3


In [88]:
#3개의 칼럼명
col_name2=['col1', 'col2', 'col3']

#2*3 리스트, ndarray 생성
list2 = [[1,  2, 3],[11, 12, 13]]
array2 = np.array(list2)
print("array2 shape:", array2.shape)
# 2차원 리스트 -> DataFrame
df_list2 = pd.DataFrame(list2, columns=col_name2)
print("2차원 리스트로 만든 DataFrame:\n", df_list2)

# 2차원 ndarray -> DataFrame
df_array2 = pd.DataFrame(array2, columns=col_name2)
print("2차원 ndarray로 만든 DataFrame:\n", df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [90]:
#딕셔너리

dict = {'col1': [1,11], 'col2': [2,22], 'col3': [3, 33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33


In [92]:
#DataFrame -> ndarray
array3 = df_dict.values
print(type(array3), '\n',array3)

#tolist
list3=df_dict.values.tolist()
print(type(list3),"\n", list3)

#todict
list4=df_dict.to_dict('list')
print(type(list4), '\n', list4)

<class 'numpy.ndarray'> 
 [[ 1  2  3]
 [11 22 33]]
<class 'list'> 
 [[1, 2, 3], [11, 22, 33]]
<class 'dict'> 
 {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [105]:
#칼럼 생성

titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [ ]:
#기존 칼럼 사용
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)


In [ ]:
##업데이트
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

In [108]:
#칼럼 삭제

titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [109]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [110]:
#inplace=True로 하여 원본 수정
drop_result = titanic_df.drop('Age_0', axis=1, inplace=True)
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [112]:
#axis=0으로 설정해 index 0, 1, 2(맨 앞 3개  데이터) 로우를 삭제

pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('####debore axis 0 drop#####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print("###after axis 0 drop####")
print(titanic_df.head(3))

####debore axis 0 drop#####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
###after axis 0 drop####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


In [114]:
#인덱스
titanic_df = pd.read_csv('train.csv')

In [117]:
#인덱스 객체 추출
indexes = titanic_df.index
print(indexes)
#array로
print("array: ", indexes.values)

RangeIndex(start=0, stop=891, step=1)
array:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 

In [119]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])


<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [120]:
#seires 연산
series_fair = titanic_df['Fare']
print("최대:", series_fair.max())
print("합:", series_fair.sum())
print("Sum() Fair Series:", sum(series_fair))
print("Fair series + 3:\n:", (series_fair+3).head(3))

최대: 512.3292
합: 28693.9493
Sum() Fair Series: 28693.9493
Fair series + 3:
: 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [121]:
#reset_index

titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [122]:
#reset_index는 숫자형 index로 만들고 싶을 때
print('## before reset_index ##')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print("value_counts 객체 변수 타입:", type(value_counts))

# reset_index (새 DataFrame 반환)
new_value_counts = value_counts.reset_index(inplace=False)

print('### After reset_index ###')
print(new_value_counts)
print("new_value_counts 객체 변수 타입:", type(new_value_counts))


## before reset_index ##
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


In [124]:
#데이어 추출
print(titanic_df['Pclass'].head(3))
print(titanic_df[['Survived', 'Pclass']].head(3))
print('[ ]안의 숫자 index는 KeyErroer 오류 발생: \n', titanic_df[0])

0    3
1    1
2    3
Name: Pclass, dtype: int64
   Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

In [125]:
titanic_df[0:2] ##숫자는 안되지만 슬라이싱과 불린은 가능

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [127]:
titanic_df[titanic_df["Pclass"] ==3 ].head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

In [129]:
#iloc[ ]
#index를 one, two, three, four로 변경
data = {'Name': ['Chulmin', 'Eunkyung', 'Inwoong', 'Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
        }

data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])
print(data_df)

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three   Inwoong  2015    Male
four    Soobeom  2015    Male


In [131]:
data_df.iloc[0,0]

'Chulmin'

In [132]:
data_df.iloc[0, 'Name'] ##-> 오류남

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [133]:

##슬라이싱 -1 활용
print("\n맨 마지막 칼럼 데이터 [:, -1]\n", data_df.iloc[:, -1])

print("\n맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1]\n", data_df.iloc[:, :-1])


맨 마지막 칼럼 데이터 [:, -1]
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1]
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three   Inwoong  2015
four    Soobeom  2015


In [134]:
data_df.loc['one', 'Name'] ##[0, 'Name']은 오류

'Chulmin'

In [135]:
print('위치기반 슬라이싱\n', data_df.iloc[0:1, 0],'\n')
print('이름기반 슬라이싱\n', data_df.loc['one':'two', 'Name'])

위치기반 슬라이싱
 one    Chulmin
Name: Name, dtype: object 

이름기반 슬라이싱
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object


In [137]:
#불린
titanic_df = pd.read_csv('train.csv')
titanic_boolean = titanic_df[titanic_df['Age']>60]
print(type(titanic_df))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [138]:
#나이가 60넘는 사람들의 이름과 나이 칼럼
titanic_df[titanic_df['Age'] > 60][['Name','Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [139]:
titanic_df.loc[titanic_df['Age']>60, ['Age', 'Name']].head(3) ##loc[ 로우 조건, 칼럼]

Age            Name
33  66.0  Wheadon, Mr...
54  65.0  Ostby, Mr. ...
96  71.0  Goldschmidt...

In [140]:
##여러가지 조건 한번에 하는 방법 1
titanic_df[ (titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex'] == 'female') ]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [141]:
##여러가지 조건 한번에 하는 방법 2 (변수)
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'

result = titanic_df[cond1 & cond2 & cond3]
print(result)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN


In [142]:
##정렬 sort_values(by=[])
titanic_sorted = titanic_df.sort_values(by=["Name"])
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [143]:
##여러개 칼럼 내림차순
titanic_sorted = titanic_df.sort_values(by=["Name", "Pclass"], ascending =False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0         345777   9.5000   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2       A/5. 851  14.5000   NaN        S
361          362         0       2  del Carlo, ...  male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C

In [145]:
##Aggregation 함수 적용
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [146]:
titanic_df[['Age','Fare']].mean() ##해당 칼럼들의 평균만

Age     29.699118
Fare    32.204208
dtype: float64

In [149]:
#groupby()
#groupby()에서 aggreagation 함수 호출
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))
titanic_groupby = titanic_df.groupby(by='Pclass').count()
titanic_groupby

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [150]:
##특정칼럼만 함수 적용
titanic_groupby = titanic_df.groupby(by='Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby


PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [151]:
##Pclass 기준으로 분류된 각 카테고리에서 Age의 최대 최소
titanic_df.groupby('Pclass')['Age'].agg([max, min])

/tmp/ipython-input-603284314.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min])
/tmp/ipython-input-603284314.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min])


max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [152]:
##Pclass 기준으로 분류된 각 카테고리에서 각 칼럼에 다른 함수 적용
agg_format = {'Age':'max', 'Fare':'mean'} ##문자열로 감싸야함
titanic_df.groupby("Pclass").agg(agg_format)

Age       Fare
Pclass                 
1       80.0  84.154687
2       70.0  20.662183
3       74.0  13.675550

In [153]:
##결손데이터 처리
#isna()
titanic_df.isna().sum()


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [154]:
#fillna() 대체
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C00')
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   C00        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   C00        S

In [157]:
#Age NaN -> 평균
#Embarked NaN -> 'S'

titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [158]:
##**apply lambda
lambda_square = lambda x : x ** 2
print('3의 제곱은:', lambda_square(3))

3의 제곱은: 9


In [160]:
##apply lambda 여러 인자
a = [1, 2, 3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [162]:
#'Name len' 칼럼 생성 & apply lambda 식으로 데이터 값 부여
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [165]:
##if else
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x < 15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [164]:
#if else 식으로 새로운 'Age_Cat'칼럼 나이가 15세 이하면 Child, 15~60세 사이는 Adult, 61세 이상 Elderly
titanic_df['Age_Cat'] = titanic_df['Age'].apply(lambda x: 'Child' if x <= 15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_Cat'].value_counts()

Age_Cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [168]:
#나이에 따라 세분화하는 함수

def get_category(age):
	cat = ""

	if age <= 5: cat = 'Baby'
	elif age <= 12 : cat = "Child"
	elif age <= 18 : cat = 'Teenager'
	elif age <= 25: cat = 'Student'
	elif age <= 35: cat = 'Young Adult'
	elif age <= 60: cat = 'Adult1'
	else :   cat = 'Elderly'

	return cat

#칼럼 만들기
titanic_df['Age_Cat'] = titanic_df['Age'].apply(lambda x: get_category(x))
titanic_df[['Age', 'Age_Cat']].head()

Age      Age_Cat
0  22.0      Student
1  38.0       Adult1
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult