# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [4]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [5]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [7]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [9]:
vector_range =np.arange(10,50)
print(vector_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [14]:
vector_range =np.arange(10)
print(vector_range[::-1])

[9 8 7 6 5 4 3 2 1 0]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [15]:
matrix_list = np.arange(9).reshape(3,3)
print(matrix_list)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [35]:
non_zero_indices = np.nonzero([1,2,0,0,4,0])
print(non_zero_indices)

(array([0, 1, 4]),)


### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [17]:
idenity_matrix = np.eye(3)
print(idenity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [18]:
array3 = np.random.random((3,3,3))
print(array3)

[[[0.56610889 0.92562735 0.80792551]
  [0.15023482 0.61097729 0.63757321]
  [0.90978608 0.67716939 0.77766155]]

 [[0.90370166 0.06760338 0.41855905]
  [0.09232939 0.10487876 0.60948805]
  [0.29957255 0.53417956 0.10651368]]

 [[0.10511385 0.43990595 0.41594367]
  [0.58364823 0.3058847  0.60183197]
  [0.79093911 0.4256344  0.79864469]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [20]:
array10 = np.random.random((10,10))
min_value = np.min(array10)
max_value = np.max(array10)
print(min_value, max_value)

0.01612786325007265 0.9977077063144176


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [21]:
array30 = np.random.random(30)
mean_value = np.mean(array30)
print(mean_value)

0.42900435220455896


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [23]:
array2d = np.ones((10,10))
array2d[1:-1,1:-1] = 0
print(array2d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [34]:
array_before = np.ones((5,5))
print('#before\n',array_before)
array_before[1:4,1:4] = 0
print('\n#after\n',array_before)

#before
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

#after
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [39]:
print(0 * np.nan) # 결과 이유: NaN과의 모든 산술 연산 결과는 NaN
print(np.nan == np.nan) # 결과 이유: NaN은 자기 자신과 같지 않으므로 결과는 False
print(np.inf > np.nan) # 결과 이유: NaN과의 비교 연산 결과는 False
print(np.nan - np.nan) # 결과 이유: NaN과의 산술 연산 결과는 NaN
print(np.nan in set([np.nan])) # 결과 이유: set에서는 NaN을 동일하게 처리하므로 결과는 True
print(0.3 == 3 * 0.1) # 결과 이유: 부동소수점 연산의 한계로 인해 정확히 0.3이 되지 않아 결과는 False

nan
False
False
nan
True
False


### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [40]:
norm_array = np.random.random((5,5))
norm_array = (norm_array - np.mean(norm_array)) / np.std(norm_array)
print(norm_array)

[[-0.66341743  1.24354188 -1.47049887 -1.61199895  0.68380053]
 [-0.07421598  0.85308638  1.31636688  1.04084308 -0.15670289]
 [-1.43666465  0.96683937  1.15575474  0.18588311 -1.36266859]
 [ 0.96119985 -1.39586228  0.49377483  0.10033475 -1.58223076]
 [-0.3103386   0.29446479 -0.73778272  1.24985942  0.25663211]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [42]:
A= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
B= np.array([[1,2],[3,4],[5,6]])
print(np.dot(A,B))

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [46]:
print(np.array(0) / np.array(0))
# 결과 이유: NumPy 배열에서 0을 0으로 나누면 결과는 NaN (Not a Number)이 됨. 수학적으로 정의가 안 되어 있기 때문.
print(np.array(0) // np.array(0))
# 결과 이유: NumPy 배열에서 0을 0으로 정수 나눗셈 (//) 하면 결과는 0이 됨.
print(np.array([np.nan]).astype(int).astype(float))
# 결과 이유: np.array([np.nan])을 정수형으로 변환할 때, NaN은 유효한 정수 표현이 없으므로 시스템에 따라 특정 값으로 변환됨.

nan
0
[-9.22337204e+18]


/tmp/ipython-input-2818962244.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-2818962244.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-2818962244.py:5: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [47]:
array5 = np.zeros((5,5))
array5 += np.arange(5)
print(array5)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [48]:
ran_vector = np.random.random(10)
ran_vector.sort()
print(ran_vector)

[0.08074052 0.08400918 0.25258866 0.34111821 0.49134254 0.58531283
 0.75591627 0.79750905 0.87042276 0.90629101]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [3]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [49]:
print(pd.__version__)

2.2.2


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [65]:
# 문제 풀이 전 numpy 임포트
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [67]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [68]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [69]:
print(df['animal'])
print(df['age'])

a      cat
b      cat
c    snake
d      dog
e      dog
f      cat
g    snake
h      cat
i      dog
j      dog
Name: animal, dtype: object
a    2.5
b    3.0
c    0.5
d    NaN
e    5.0
f    2.0
g    4.5
h    NaN
i    7.0
j    3.0
Name: age, dtype: float64


### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [74]:
print(df['animal'].iloc[[3,4,8]])
print(df['age'].iloc[[3,4,8]])

d    dog
e    dog
i    dog
Name: animal, dtype: object
d    NaN
e    5.0
i    7.0
Name: age, dtype: float64


### 9. Select only the rows where the number of visits is greater than 3.

In [79]:
selected = df[df['visits']>=3]
print(selected)


  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no


### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [80]:
selected = df[df['age'].isnull()]
print(selected)

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [81]:
selected = df[(df['animal'] == 'cat') & (df['age'] < 3)]
print(selected)

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no


### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [128]:
if '(f, age)' in df.columns:
    df = df.drop(columns=['(f, age)'],inplace=True)
selected = df[(df['age'] >= 2) & (df['age'] <= 4)]
print(selected)

  animal  age visits priority
a    cat  2.5      1      yes
b    cat  3.0      3      yes
j    dog  3.0      1       no


### 13. Change the age in row 'f' to 1.5.

In [127]:
df.loc['f', 'age'] = 1.5
print(df)

  animal  age visits priority
a    cat  2.5      1      yes
b    cat  3.0      3      yes
c  snake  0.5      2       no
d    dog  NaN      3      yes
e    dog  5.0      2       no
f    cat  1.5      3       no
g  snake  4.5      1       no
h    cat  NaN      1      yes
i    dog  7.0      2       no
j    dog  3.0      1       no


### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [91]:
sum_visits = df['visits'].sum()
print(sum_visits)

19


### 15. Calculate the mean age for each different animal in `df`.

In [92]:
mean_age = df.groupby('animal')['age'].mean()
print(mean_age)

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64


### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [126]:
df.drop(columns=[('f', 'age')], inplace=True)
df.loc['k']=['cat',5,3,'no']
print(df)
df = df.drop('k')
print(df)

  animal  age visits priority
a    cat  2.5      1      yes
b    cat  3.0      3      yes
c  snake  0.5      2       no
d    dog  NaN      3      yes
e    dog  5.0      2       no
f    cat  1.5      3       no
g  snake  4.5      1       no
h    cat  NaN      1      yes
i    dog  7.0      2       no
j    dog  3.0      1       no
k    cat    5      3       no
  animal  age visits priority
a    cat  2.5      1      yes
b    cat  3.0      3      yes
c  snake  0.5      2       no
d    dog  NaN      3      yes
e    dog  5.0      2       no
f    cat  1.5      3       no
g  snake  4.5      1       no
h    cat  NaN      1      yes
i    dog  7.0      2       no
j    dog  3.0      1       no


### 17. Count the number of each type of animal in `df`.

In [129]:
count_ani = df['animal'].value_counts()
print(count_ani)

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64


18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [140]:
df_sorted = df.sort_values(
    by=['age', 'visits'],
    ascending=[False, True]   )

print(df_sorted)

  animal  age visits priority
i    dog  7.0      2       no
e    dog  5.0      2       no
g  snake  4.5      1       no
j    dog  3.0      1       no
b    cat  3.0      3      yes
a    cat  2.5      1      yes
f    cat  1.5      3       no
c  snake  0.5      2       no
h    cat  NaN      1      yes
d    dog  NaN      3      yes


### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [141]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
print(df)

  animal  age visits  priority
a    cat  2.5      1      True
b    cat  3.0      3      True
c  snake  0.5      2     False
d    dog  NaN      3      True
e    dog  5.0      2     False
f    cat  1.5      3     False
g  snake  4.5      1     False
h    cat  NaN      1      True
i    dog  7.0      2     False
j    dog  3.0      1     False


### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [142]:
df['animal'] = df['animal'].replace('snake', 'python')
print(df)

   animal  age visits  priority
a     cat  2.5      1      True
b     cat  3.0      3      True
c  python  0.5      2     False
d     dog  NaN      3      True
e     dog  5.0      2     False
f     cat  1.5      3     False
g  python  4.5      1     False
h     cat  NaN      1      True
i     dog  7.0      2     False
j     dog  3.0      1     False


In [143]:
# 확인용 df 출력 셀
df

animal  age visits  priority
a     cat  2.5      1      True
b     cat  3.0      3      True
c  python  0.5      2     False
d     dog  NaN      3      True
e     dog  5.0      2     False
f     cat  1.5      3     False
g  python  4.5      1     False
h     cat  NaN      1      True
i     dog  7.0      2     False
j     dog  3.0      1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [145]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))
df = df.sub(df.mean(axis=1), axis=0)
print(df)





          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278
