In [39]:
import sklearn
print(sklearn.__version__)

1.6.1


In [40]:
# 모듈 임포트하기
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

### 붓꽃 품종 예측하기

In [41]:
# DF로 변환해 피처와 데이터 값 구성 알아보기
import pandas as pd

# 붓꽃 데이터세트 로딩
iris = load_iris() 

# iris.data: iris 데이터 세트에서 피처만으로 구성된 데이터를 numpy로 가진다
# 꽃잎의 길이와 너비, 꽃받침의 너비와 길이 피처(입력변수)를 numpy 배열 형태로 저장했다는 뜻
iris_data = iris.data

# iris.target: 붓꽃 데이터 세트에서 label(각 데이터의 결정값) 데이터를 numpy로 가진다
# 0, 1, 2 세 가지 숫자로 되어 있고, 각각이 꽃 종류(Setosa, Versicolor, Virginica)를 의미
iris_label = iris.target
print('iris target 값:', iris_label)
print('iris target 명:', iris.target_names)

# 붓꽃 데이터셋을 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

iris: 사이킷런이 제공하는 Bunch 객체 <br>
load_iris()가 반환하는 이 Bunch 안에는 여러 가지 속성이 포함됨. 

- iris.data → 피처값 (numpy 배열)
- iris.target → 정답값 (numpy 배열)
- iris.feature_names → 피처 이름 (리스트: ["sepal length", ...])
- iris.target_names → 정답 이름 (리스트: ["setosa", "versicolor", "virginica"])
- iris.DESCR → 데이터셋 설명 텍스트

--- 
iris.target = 넘파이 배열 (정답 값)
iris_label = 위 배열을 복사한 변수
iris.target_names = 정답 값(0/1/2)에 대응하는 품종 이름표

In [42]:
# 학습용, 테스트용 데이터 분리하기
# train_test_split() API 활용: 각각의 데이터를 test_size 파라미터 입력값의 비율로 분할함 
# test_size=0.2 라고 설정하면 전체 데이터 중 테스트 데이터를 20%, 학습 데이터를 80%로 데이터를 분할함

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)


- 첫 번째 입력 파라미터 iris_data: **피처 데이터 세트**  (X)
- 두 번째 입력 파라미터 iris_label: **label 데이터 세트** (y)
- test_size는 위 주석의 내용과 같음. 여기서는 테스트 데이터 20% 활용한단 뜻.
- 네 번째 입력 파라미터 random_state=11: 호출 시마다 같은 학습/테스트용 데이터셋을 생성하기 위해 주어지는 난수 발생 값. 이를 지정하지 않으면 train_test_split 수행할 때마다 다른 데이터를 생성하게 됨. (숫자는 아무 값 지정해도 됨.)

In [43]:
# 의사결정트리 이용해 데이터에 대한 학습과 예측 수행하기 
# 사이킷런의 의사결정트리 클래스를 객체로 생성
dt_clf = DecisionTreeClassifier(random_state=11) 

# 학습 수행
# fit() 메서드에 학습용 피처 데이터 속성, 결정값 데이터셋 입력해 호출하면 학습 수행함.
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

👆🏻 학습 데이터(X_train, y_train)를 바탕으로 학습을 완료한 상황. 이렇게 학습된 DecisionTreeClassifier 객체를 이용해 **예측** 을 수행한다. <br>
예측: 반드시 학습데이터가 아닌 다른 데이터!! 를 이용해야 하며, 일반적으로 테스트 데이터 세트를 활용한다. <br>
의사결정트리 객체의 `predict()` 메서드에 이 데이터 세트를 입력해 호출하면, 학습된 모델 기반에서 테스트 데이터셋에 대한 예측값을 반환한다.

In [44]:
# 학습 완료된 의사결정트리 객체에서 테스트 데이터 세트로 예측 수행하기
pred = dt_clf.predict(X_test)

In [45]:
# DTC의 예측 성능 평가하기: 정확도 accuracy_score() 
# 예측한 붓꽃 품종과 실제 테스트 데이터 세트의 붓꽃 품종이 일치하는 정도

from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


### 사이킷런 기반 프레임워크 익히기

In [46]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [47]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 Key:', keys)

붓꽃 데이터 세트의 Key: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [48]:
# load_iris()가 반환하는 객체의 키들이 가리키는 값들

# 1. feature_names
print('feature_names의 타입:', type(iris_data.feature_names))
print('feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

# 2. target_names
print('\ntarget_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

# 3. data
print('\ndata의 type:', type(iris_data.data))
print('data의 shape:', len(iris_data.data))
print(iris_data['data'])

# 4. target
print('\ntarget의 type:', type(iris_data.target))
print('target의 shape:', len(iris_data.target))
print(iris_data.target)

feature_names의 타입: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

data의 type: <class 'numpy.ndarray'>
data의 shape: 150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2

### Model Selection 모듈

In [89]:
# 학습 데이터셋으로만 학습하고 예측하는 경우 (동일한 데이터셋으로 학습+예측 수행
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label) # 모델 학습용 메서드 fit()

# 학습 데이터셋으로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))

예측 정확도: 1.0


예측 결과가 100% 정확하게 출력되었다. 이미 학습한 학습 데이터 세트를 기반으로 예측했기 때문이다. <br>
학습을 수행한 데이터 세트가 아닌 **테스트 전용** 데이터 세트를 활용해야 한다. → train_test_split()을 통해 원본 데이터 세트에서 학습/테스트용을 쉽게 분리할 수 있다. 

X 계열 = 입력값(피처) <br>
y 계열 = 정답값(레이블) <br>
train = 모델이 배우는 데 쓰는 데이터 <br>
test = 모델이 잘 배웠는지 시험하는 데 쓰는 데이터 <br>

In [55]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier() 
iris_data = load_iris()

# test_train_split(피처 데이터셋, 레이블 데이터셋)
# 테스트 데이터셋을 30%로, random_state를 121로
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

# data는 각 피처의 수치(꽃잎 길이.. etc)고 target은 0, 1, 2 값 

In [58]:
# 위의 학습 데이터를 기반으로 DTC를 학습하고 (fit 메서드) 이 모델을 이용해 예측 정확도를 측정하기

# 학습용 입력 데이터와 정답을 이용해 규칙을 학습함
dt_clf.fit(X_train, y_train)

# 학습이 완료된 모델에 테스트 데이터 세트를 넣음 - 0, 1, 2로 구성된 배열이 pred에 저장됨
pred = dt_clf.predict(X_test)


print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556


dt_clf.fit(X_train, y_train)에서는 **y_train**이 정답 역할을 한다. (교과서 느낌) <br>
accuracy_score(y_test, pred)에서는 X_test에 대해 모델이 낸 예측(pred)을 실제 정답(**y_test**)과 비교해서 맞췄는지 확인한다. 

---
y_train = 학습 단계에서 쓰는 정답 (모델이 배울 때 참고) <br>
y_test = 평가 단계에서 쓰는 정답 (모델이 제대로 배웠는지 채점할 때 사용)

#### 교차 검증

#### K 폴드 교차 검증

In [65]:
# 1. K 폴드 교차 검증: KFold 클래스 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# K=5인 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [69]:
# 생성된 KFold 객체에 split()을 호출해 전체 붓꽃 데이터를 5개의 데이터 폴드 세트로 분리 
# 150개 중 4/5인 120개를 학습, 1/5인 30개를 검증 테스트 데이터 세트로 활용
# split()을 호출해 교차 검증 수행 시마다 학습/검증을 반복해 예측 정확도를 측정

n_iter = 0

# KFold 객체의 split()을 호출하면 폴드별 학습용, 검증용 테스트의 로우 인덱스를 배열로 반환
for train_index, test_index in kfold.split(features): 
    # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    # 반복 시마다 정확도 측정하기
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy) 

# 개별 반복별 정확도를 합해 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도: 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도: 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도: 0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


검증 세트의 인덱스를 보면 0-29, 30-59... 처럼 30개씩 각각의 검증 세트 인덱스가 생성되고 있으며, 이를 기반으로 검증 세트가 추출되고 있다는 걸 알 수 있다. 

#### Stratified K 폴드

In [72]:
# K 폴드의 한계를 먼저 확인... 
# 붓꽃 데이터셋을 DF로 생성하고 레이블 값의 분포도 확인
import pandas as pd
iris = load_iris()
ifis_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [78]:
# 위의 코드에서 각각의 레이블이 50개로 동일하게 출력되었다. 
# 3개의 폴드 세트를 KFold로 생성하고, 교차 검증 시마다 각각 생성되는 학습/검증 데이터 값의 분포를 확인해 보기
kfold = KFold(n_splits=3)
n_iter=0

# 각 반복마다 학습용 인덱스 / 검증용 인덱스를 반환
for train_index, test_index in kfold.split(iris_df): 
    n_iter += 1

    # 학습 세트와 검증 세트의 레이블(정답, 품종 번호)을 꺼내옴 
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())
    print('\n')

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    50
Name: count, dtype: int64


## 교차 검증: 2
학습 레이블 데이터 분포:
 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    50
Name: count, dtype: int64


## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    50
Name: count, dtype: int64




전체 붓꽃 데이터 150개에서 데이터 폴드 3개 생성 - 100개의 학습 데이터와 50개의 검증 데이터 <br>
이때, 교차 검증 시마다 학습 레이블과 검증 레이블이 완전히 다른 값으로 추출된 것을 볼 수 있다. <br>
예를 들어 교차검증 #1에서, 학습 세트에 1과 2만 있다. 이러면 모델은 0이라는 게 존재한다는 걸 모르게 된다. 
검증 세트에는 0만 있는데, 그럼 모델은 절대 맞힐 수 없게 되는 것이다. => 검증 예측 정확도 0
<br> 
이 문제를 StratifiedKFold가 해결함.

In [80]:
# split 메서드에 인자로 레이블 데이터 세트도 포함해야 한다. 
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())
    print('\n')

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64


## 교차 검증: 2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64


## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64




학습 레이블과 검증 레이블 데이터 값의 분포도가 거의 동일하게 할당되었음을 알 수 있다. 이렇게 분할되어야 레이블 값 0, 1, 2를 모두 학습하고 이에 기반해 검증을 수행할 수 있다!!

In [87]:
# StratifiedKFold 이용해 붓꽃 데이터 교차 검증하기

# 데이터 분리
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

# StratifiedKFold의 split()을 호출할 땐 레이블 데이터 세트도 반드시 넣어 주어야 한다 (KFold는 피처 데이터셋만 입력)
for train_index, test_index in skfold.split(features, label):
    # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index] 
    y_train, y_test = label[train_index], label[test_index]

    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)

    # 반복마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

print('=======================================================================')

# 교차 검증별 정확도 및 평균 정확도 계산
print('## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.round(np.mean(cv_accuracy), 4))


#1 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도: 0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9667


#### cross_val_score()

In [88]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표: accuracy / 교차 검증 세트 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


#### GridSearchCV: 교차 검증 + 하이퍼 파라미터 튜닝

In [94]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1, 2, 3], 'min_samples_split':[2, 3]}

In [97]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
# refit=True가 디폴트. true면 가장 좋은 파라미터 설정으로 재학습시킴
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]


params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [98]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [99]:
# GridSearchCV의 ref it 으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0: .4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667


### 데이터 전처리

In [103]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 뒤, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [107]:
# 위 예제는 데이터 크기가 작아서 문자열이 어떤 숫자로 인코딩됐는지 알 수 있지만 데이터가 많은 경우에는 classes_ 속성값을 이용한다.
# 인덱스 0부터 순서대로 출력
print('인코딩 클래스:', encoder.classes_)

# transform()으로 디코딩
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [112]:
# 원핫 인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 2차원 ndarray로 변환
items = np.array(items).reshape(-1, 1)

# 원핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder로 변환한 결과를 toarray() 이용해 밀집 행렬로 변환
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('\n원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]

원-핫 인코딩 데이터 차원
(8, 6)


In [114]:
# pandas 내의 get_dummies()를 이용하면 원-핫 인코딩을 더 쉽게 사용 가능
import pandas as pd

df = pd.DataFrame({'item': ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0     True     False    False     False       False     False
1    False      True    False     False       False     False
2    False     False    False     False        True     False
3    False     False    False     False       False      True
4    False     False    False      True       False     False
5    False     False    False      True       False     False
6    False     False     True     False       False     False
7    False     False     True     False       False     False

#### StandardScaler

In [115]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 세트 로딩하고 DF로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature들의 평균 값')
print(iris_df.mean())
print('\nfeature들의 분산 값')
print(iris_df.var())


feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [118]:
# 각 피처를 한 번에 표준화해 반환
# StandardScaler 객체 생성 후, fit()과 transform() 메서드에 변환 대상 피처 데이터 세트를 입력하고 호출하면 변환됨

from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

#데이터 세트 변환, fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform 호출 시 스케일 변환된 데이터셋이 넘파이 ndarray 형태이므로 이를 DF로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산 값')
print(iris_df_scaled.var())

feature들의 평균값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### MinMaxScaler

In [122]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()
# MinMaxScaler 로 데이터 셋 변환, fit() 과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform 호출 시 스케일 변환된 데이터셋이 넘파이 ndarray 형태이므로 이를 DF로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#### 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점

In [123]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0 부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# fit(), transform()은 2차원 이상 데이터만 가능: reshape(-1, 1)로 차원 변경
train_array = np.arange(0, 11).reshape(-1, 1)
test_array =  np.arange(0, 6).reshape(-1, 1)

In [124]:
# MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1 값으로 변환됨
scaler = MinMaxScaler()

# fit()하게 되면 train_array 데이터의 최솟값 0, 최댓값 10으로 설정
scaler.fit(train_array)

# 1/10 scale로 train_array 데이터 변환함. 원본값 10이 1로 변환된다.
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [127]:
# MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값 0, 최댓값 5로 설정됨
scaler.fit(test_array)

# 1/5 scale로 test_array 데이터 변환함. 원본 5->1로 변환.
test_scaled = scaler.transform(test_array)

# test_array의 scale 변환 출력
print('원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


In [128]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

# test_array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform() 만으로 변환해야 함. 
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]
