# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [183]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [184]:
print('Numpy version:', np.__version__)
np.show_config()

Numpy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

[링크 텍스트](https://)### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [185]:
list_zero = np.zeros(9)
print(list_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [186]:
list_zero[4] = 1
print(list_zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [187]:
range_vector = np.arange(start = 10, stop = 50)
print(range_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [188]:
reverse_vector = np.arange(10)[::-1]
print(reverse_vector)

[9 8 7 6 5 4 3 2 1 0]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [189]:
matrix_33 = np.arange(9).reshape(3, -1)
print(matrix_33)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [190]:
elements = np.array([1,2,0,0,4,0])
non_zero_indices = np.where(elements != 0)
print(non_zero_indices)

(array([0, 1, 4]),)


### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [191]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [192]:
print(np.random.rand(3,3))

[[0.29280939 0.61091433 0.91302739]
 [0.300115   0.24859864 0.6663921 ]
 [0.98753291 0.46827041 0.12328738]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [193]:
random = np.random.rand(10,10)
print(random.min(), random.max())

0.014627352824220452 0.9914673999458862


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [194]:
print(np.random.rand(10).mean())

0.40961057639222587


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [195]:
arr = np.ones((10,10), dtype=int)
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [196]:
arr_ones = np.ones((5,5))
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [197]:
arr_ones[:] = 0
arr_ones[1:-1, 1:-1] = 1
print(arr_ones)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [198]:
print(0 * np.nan) ## NaN은 숫자가 아님 NaN의 연산은 항상 NaN을 반환
print(np.nan == np.nan) ##Nan은 자기 자신과도 같지 않다고 정의되어 있음
print(np.inf > np.nan) ## NaN과의 비교 연산은 항상 False를 반환
print(np.nan - np.nan) ##NaN과의 연산은 항상 NaN을 반환
print(np.nan in set([np.nan]))
##set[]은 원소를 해시값을 기준으로 관리, np.nan의 해시값은 0으로 계산
##np.nan in 을 시행할 때 np.nan의 해시값 계산
##집합 안에 동일한 해시값을 가진 원소가 있는지 확인
##있으면 True
print(0.3 == 3 * 0.1)##이진법에서 0.1은 표현이 안되는 무한소수로 0.1*3은 0.3000000004처럼 표현

nan
False
False
nan
True
False


### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [199]:
x = np.random.rand(5,5)
mean = np.mean(x)
std = np.std(x)

z = (x - mean) / std
print(z)

[[-0.40112938  1.65383085 -0.69005331  0.89635042  0.09929766]
 [ 1.53846949  0.69642343 -1.33313055 -0.70003486 -0.94964239]
 [ 0.58898271 -1.3694713  -0.43350393  0.07397449  1.06148755]
 [-1.45925756  0.47000041  0.40814425 -1.42083631 -0.98029717]
 [ 1.11433126 -0.67333258 -0.80319823  1.28163253  1.33096253]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [200]:
arr1 = np.ones((5,3))
arr2 = np.ones((3,2))
arr3 = np.dot(arr1, arr2)
print(arr3)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [201]:
print(np.array(0) / np.array(0)) ## 부동소수점 규칙에 따라 0 / 0 은 수학적으로 정의되지 않은 연산. Not a number
print(np.array(0) // np.array(0)) ##내부 구현으로 경고 후 하고 0(undefined)을 반환
print(np.array([np.nan]).astype(int).astype(float))
##nan이 들어간 float 배열
##int로 바꾸려고 시도하지만 nan은 부동소수점 값. 정수로 표현 안됨
##경고를 띄우고 int64의 최솟값으로 대체 후 float으로 변경

nan
0
[-9.22337204e+18]


/tmp/ipython-input-4220037545.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) ## 부동소수점 규칙에 따라 0 / 0 은 수학적으로 정의되지 않은 연산. Not a number
/tmp/ipython-input-4220037545.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) ##내부 구현으로 경고 후 하고 0(undefined)을 반환
/tmp/ipython-input-4220037545.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [202]:
a = np.tile(np.arange(5), (5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [203]:
print(np.sort(np.random.rand(10)))

[0.02558034 0.30236034 0.36025864 0.42968256 0.46831326 0.60023802
 0.61796577 0.71882254 0.77221471 0.86813847]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [204]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [205]:
print(pd.__version__)

2.2.2


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [206]:
# 문제 풀이 전 numpy 임포트
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


data_df = pd.DataFrame(data, index =labels)
print(data_df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [207]:
print(data_df.info)

<bound method DataFrame.info of   animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no>


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [208]:
print(data_df.describe)

<bound method NDFrame.describe of   animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no>


### 6. Return the first 3 rows of the DataFrame `df`.

In [209]:
print(data_df.head(3))

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no


### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [210]:
print(data_df[['age','animal']])

   age animal
a  2.5    cat
b  3.0    cat
c  0.5  snake
d  NaN    dog
e  5.0    dog
f  2.0    cat
g  4.5  snake
h  NaN    cat
i  7.0    dog
j  3.0    dog


### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [211]:
data_df[['animal', 'age']].iloc[[3,4,8],]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [212]:
data_df[data_df['visits']>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [213]:
data_df[data_df['age'].isna() == True]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [214]:
data_df[(data_df['animal'] == 'cat') & (data_df['age'] < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [215]:
data_df[data_df['age'].between(2, 4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [216]:
data_df.loc['f', 'age'] = 1.5
data_df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [217]:
print(data_df['visits'].sum())

19


### 15. Calculate the mean age for each different animal in `df`.

In [218]:
data_df1 = data_df.groupby(by = ['animal'])
print(data_df1['age'].mean())

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64


### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [219]:
data_df['k'] = 0
data_df_k = data_df
print(data_df_k)
data_df.drop('k', axis=1, inplace=True)
data_df

  animal  age  visits priority  k
a    cat  2.5       1      yes  0
b    cat  3.0       3      yes  0
c  snake  0.5       2       no  0
d    dog  NaN       3      yes  0
e    dog  5.0       2       no  0
f    cat  1.5       3       no  0
g  snake  4.5       1       no  0
h    cat  NaN       1      yes  0
i    dog  7.0       2       no  0
j    dog  3.0       1       no  0


animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in `df`.

In [220]:
print(data_df['animal'].count())

10


### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [221]:
data_df.sort_values(by=['age', 'visits'],
                    ascending=[False, True],
                    inplace=True)
print(data_df)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes


### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [222]:
data_df['priority'] = data_df['priority'].map({'yes': True, 'no' : False})
print(data_df)

  animal  age  visits  priority
i    dog  7.0       2     False
e    dog  5.0       2     False
g  snake  4.5       1     False
j    dog  3.0       1     False
b    cat  3.0       3      True
a    cat  2.5       1      True
f    cat  1.5       3     False
c  snake  0.5       2     False
h    cat  NaN       1      True
d    dog  NaN       3      True


### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [223]:
data_df.loc[data_df['animal'] == 'snake', 'animal'] = 'python'

In [224]:
# 확인용 df 출력 셀
data_df

animal  age  visits  priority
i     dog  7.0       2     False
e     dog  5.0       2     False
g  python  4.5       1     False
j     dog  3.0       1     False
b     cat  3.0       3      True
a     cat  2.5       1      True
f     cat  1.5       3     False
c  python  0.5       2     False
h     cat  NaN       1      True
d     dog  NaN       3      True

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [225]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))



In [226]:
df = df.apply(lambda x : x - x.mean(), axis=0)
print(df)

          0         1         2
0 -0.280737  0.289178  0.340872
1  0.029343 -0.210438 -0.334138
2  0.241142 -0.106057  0.372504
3  0.384759 -0.143468  0.209324
4 -0.374507  0.170784 -0.588563
