# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [68]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [69]:
print(np.__version__)
np.show_config

2.0.2


<function numpy.__config__.show(mode='stdout')>

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [70]:
# zeros 메서드 활용
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [71]:
# zeros + 단일 인덱스로 1 대입
zero = np.zeros(10)
zero[4] = 1
print(zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [72]:
array = np.arange(start=10, stop=50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [73]:
# 0부터 9까지의 ndarray 생성한 뒤 내림차순 정렬
array = np.arange(start=0, stop=10)
np.sort(array)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [74]:
# np.flip()이라는 함수를 적용해도 된다.
np.flip(array)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [75]:
array = np.arange(start=0, stop=9)
array2= array.reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [76]:
# np.nonzero() : 요소들 중 0이 아닌 값들의 index들을 반환해 주는 함수
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4]),)


기본적으로 np.nonzero()는 튜플을 반환한다.
튜플의 길이 = 배열의 차원 수 > 이 문제에서는 튜플의 길이가 1이기 때문에 array([0,1,4]), ) 같은 형태로 출력되는 것이다. <br>
2차원으로 가면 (row 인덱스, col 인덱스) 3차원으로는 (x 인덱스, y 인덱스, z 인덱스)... 이런 형태가 된다.

In [77]:
# np.where(조건) : 조건에 맞는 값의 인덱스를 반환하는 함수
# 배열을 만들고, 메서드 적용
array = np.array([1,2,0,0,4,0])
non_zero = np.where(array != 0)
print(non_zero)

(array([0, 1, 4]),)


### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [78]:
 # eye 함수는 주어진 크기의 단위 행렬이나 대각 행렬을 생성한다 - 기본적으로는 정사각 ㅎ
mat= np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [79]:
# 1. np.random.rand() 함수: [0, 1)의 범위에서 균등하게 추출하여 N차원 배열을 생성. 인자로 배열의 크기를 받는다 - 차원의 크기를 개별 숫자로
random_matrix=np.random.rand(3,3,3)
print(random_matrix)

[[[0.29280939 0.61091433 0.91302739]
  [0.300115   0.24859864 0.6663921 ]
  [0.98753291 0.46827041 0.12328738]]

 [[0.91603139 0.94614353 0.27769737]
  [0.51965369 0.154745   0.01462735]
  [0.32424321 0.99089844 0.51314129]]

 [[0.87649564 0.06739575 0.28415374]
  [0.46889927 0.76177319 0.92261178]
  [0.39302376 0.92908768 0.49961201]]]


In [80]:
# 2. np.random.random() 함수: shape을 튜플로 한 번에 전달
random_matrix = np.random.random((3,3,3)) # 튜플 형태!!
print(random_matrix)

[[[0.80204969 0.89658011 0.48212908]
  [0.8479299  0.27667928 0.34022921]
  [0.1050746  0.52314772 0.64850802]]

 [[0.89961158 0.10386594 0.31174468]
  [0.07810332 0.93787019 0.95908699]
  [0.19124218 0.95402114 0.44404827]]

 [[0.26342439 0.66989772 0.37626831]
  [0.98546613 0.6670733  0.9914674 ]
  [0.97356447 0.18145632 0.441372  ]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [81]:
rand_matrix = np.random.rand(10,10)
print(rand_matrix.min(), rand_matrix.max())

0.025222518201502453 0.9741218613820473


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [82]:
rand_matrix = np.random.rand(30)
print(rand_matrix.mean())

0.5622694980733329


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [83]:
# 우선 ones 메서드로 배열에 전부 1을 채운다.
arr = np.ones((10, 10))

# [1:-1] 슬라이싱: 양 끝을 제외한 모든 인덱스
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [84]:
# zeros 메서드로 전부 0을 채우고, 슬라이싱으로 1을 채워도 됨.
arr = np.zeros((10,10))

arr[0, :] = 1     # 첫 번째 행 전체를 1로
arr[-1, :] = 1    # 마지막 행 전체를 1로
arr[:, 0] = 1     # 첫 번째 열 전체를 1로
arr[:, -1] = 1    # 마지막 열 전체를 1로

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**콜론이 있는 자리: 해당 축(Axis)의 전체 범위** <br>
axis 0이 세로 방향(row 따라 내려옴), 1이 가로 방향(col 따라 옆으로)

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [85]:
# 13번과 동일한 원리 - ones로 전체 배열을 채운 뒤 인덱싱 활용
array = np.ones((5,5))
print('# before\n', array)

array[0,:] = array[-1,:] = array[:, 0] = array[:,-1] = 0
print('\n# after\n', array)

# before
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

# after
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [86]:
print(0 * np.nan) # NaN과의 연산산술값은 항상 NaN
print(np.nan == np.nan) # "NaN은 자기 자신과도 같지 않다"
print(np.inf > np.nan) # NaN과의 연산은 불가능함 - 비교연산 결과 항상 False
print(np.nan - np.nan) # NaN과의 연산값은 항상 NaN
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1) # 부동소수점 오차

nan
False
False
nan
True
False


### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [87]:
# 난수 배열 생성 np.random.rand()
array = np.random.rand(5,5)
mean = array.mean()
std = array.std() # 표준편차: 분산의 제곱근

norm = (array-mean)/std
print(norm)

[[-0.43375587  0.64613414  1.45301145 -0.17537695 -1.07366297]
 [ 1.60501171  0.60331567  1.72007106 -0.56358431 -1.28935163]
 [ 0.70171299 -1.38672238 -0.92454307 -0.89935918 -0.2072203 ]
 [ 0.51050985  1.14894384 -0.44416142  1.45894396 -1.59733842]
 [ 0.73744141 -0.53012484  0.42196731 -0.22129134 -1.26057071]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [88]:
# 두 행렬 모두 1로 채워져 있으면 내적으로 출력 예시와 같은 행렬이 도출됨
a = np.ones((5,3))
b = np.ones((3,2))
product = np.dot(a,b)
print(product)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [89]:
# 배열 간 나누기

# 1. 부동 소수점 연산. 0 나누기 0은 수학적으로 정의되지 않음: Not a number를 출력.
print(np.array(0) / np.array(0))

# 2. //는 나누기 연산 결과에서 소수점을 버리는 연산(정수 나눗셈) : 결과를 항상 정수 형태로 반환한다.
print(np.array(0) // np.array(0))

# 3. NaN을 리스트로 감싼 뒤, 넘파이 배열로 변환 > int 변환 > 다시 float로 변환
# NaN은 부동소수점에서만 의미가 있기 때문에 이를 정수로 변환하는 건 의미가 없는 동작 - 따라서 "일반적으로 배열의 크기나 플랫폼에 따라 임의의 큰 음수 값"을 반환한다.
# 그 값을 float형으로 반환.
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-2975727338.py:4: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-2975727338.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-2975727338.py:12: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


0 // 0 했을 때 결과가 출력되지 않는 것이 일반적인데, 넘파이에서는 "RuntimeWarning: divide by zero encountered in floor_divide"라는 오류가 뜨면서도 **0이라는 값이 출력되었다.**
넘파이에서 제공하는 예외 처리인가??

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [91]:
# [0, 1, 2, 3, 4]로 정의된 배열을 5번 반복하는 아이디어로 구현
# 'np.tile' 메서드를 활용하면 된다. np.tile([배열 정의],(행 방향 반복 횟수, 열 방향 반복 횟수)

matrix = np.tile([0,1,2,3,4], (5,1)) # row 방향으로 5번 반복되고 있으므로 (5,1)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [92]:
# 예시처럼 부동소수점으로 만들기
matrix = np.tile([0,1,2,3,4], (5,1)).astype(float)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [93]:
array = np.random.rand(10)
sorted_array = np.sort(array)
print(sorted_array)

[0.23464226 0.25930742 0.28335674 0.50876749 0.62510003 0.66174598
 0.7076653  0.81443847 0.91583146 0.92882983]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [94]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [95]:
print(pd.__version__)

2.2.2


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


In [96]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [97]:
# 문제 풀이 전 numpy 임포트
import numpy as np

# pd.DataFrame(data, column)
df = pd.DataFrame(data, index=labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


**pd.DataFrame(data, column)**

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [99]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [100]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [101]:
# 'animal'과 'age' 컬럼 선택
df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [102]:
df.iloc[[3, 4, 8], [0, 1]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [103]:
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [104]:
df[df['age'].isna()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [105]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [106]:
df[df['age'].between(2, 4, inclusive='both')]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [109]:
df.loc['f', 'age'] = 1.5
print(df.loc['f'])

animal      cat
age         1.5
visits        3
priority     no
Name: f, dtype: object


### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [107]:
df['visits'].sum()

np.int64(19)

### 15. Calculate the mean age for each different animal in `df`.

In [108]:
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [110]:
df.loc['k'] = ['cat', 2.0, 1, 'yes']
df = df.drop('k')

### 17. Count the number of each type of animal in `df`.

In [111]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [112]:
# age를 내림차순, visits를 오름차순으로 정렬
df.sort_values(by=['age', 'visits'], ascending=[False, True])

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [113]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})

### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [114]:
df['animal'] = df['animal'].replace('snake', 'python')

In [115]:
# 확인용 df 출력 셀
df

animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [116]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))

In [117]:
#  각 행의 평균을 빼기
df.sub(df.mean(axis=1), axis=0)

0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278