# 넘파이

## 넘파이 ndarray 개요

In [3]:
import numpy as np

array1 = np.array([1, 2, 3])
print('array1 type：', type(array1))
print('array 1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type：', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type：', type(array3))
print('array3 array 형태:', array3.shape)

array1 type： <class 'numpy.ndarray'>
array 1 array 형태: (3,)
array2 type： <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type： <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


## ndarray의 데이터 타입

In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [8]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [10]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

In [11]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [12]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape()

In [13]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [15]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

In [17]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [18]:
print('맨 뒤의 값:',array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [19]:
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [20]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [21]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [22]:
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [24]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [25]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [26]:
array1d=np.arange(start=1,stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:',array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [27]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [28]:
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [29]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


## 행렬의 정렬 - sort()와 argsort()

In [4]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)
# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)
# ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [5]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [6]:
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [7]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [8]:
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [9]:
import numpy as np

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [10]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array(([7,8],[9,10],[11,12]))
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [11]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


# 데이터 핸들링 - 판다스

## 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

In [12]:
import pandas as pd

In [ ]:
titanic_df=pd.read_csv(r'C:\Users\titanic_train.csv')
titanic_df.head(3)

In [ ]:
titanic_df=pd.read_csv('titanic_train.csv')
print('titanic 변수 type:',type(titanic_df))
titanic_df

In [ ]:
titanic_df.head(3)

In [ ]:
print('DataFrame 크기: ',titanic_df.shape)

In [ ]:
titanic_df.info()

In [ ]:
titanic_df.describe()

In [ ]:
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)

In [ ]:
titanic_pclass=titanic_df['Pclass']
print(type(titanic_pclass))

In [ ]:
titanic_pclass.head()

In [ ]:
value_counts=titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

In [ ]:
print('titanic_df 데이터 건수:',titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

## DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

In [14]:
import numpy as np

col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
print('array1 shape:',array1.shape)
# 리스트를 이용해 DataFrame 생성
df_list1=pd.DataFrame(list1,columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n',df_list1)
# 넘파이 ndarray를 이용해 DataFrame 생성
df_array1=pd.DataFrame(array1,columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n',df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [15]:
# 3개의 칼럼명이 필요
col_name2=['col1','col2','col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환
list2=[[1,2,3],[11,12,13]]
array2=np.array(list2)
print('array2 shape:',array2.shape)
df_list2=pd.DataFrame(list2,columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n',df_list2)
df_array2=pd.DataFrame(array2,columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n',df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [16]:
# Key는 문자열 칼럼명으로 매핑, Value는 리스트 형(또는 ndarray) 칼럼 데이터로 매핑
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n',df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [17]:
# DataFrame을 ndarray로 변환
array3=df_dict.values
print('df_dict.values 타입:',type(array3),'df_dict.avlues shape:',array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.avlues shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [18]:
# DataFrame을 리스트로 변환
list3=df_dict.values.tolist()
print('df_dict.values.tolist() 타입:',type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
dict3=df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:',type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


## DataFrame의 칼럼 데이터 세트 생성과 수정

In [ ]:
titanic_df['Age_0']=0
titanic_df.head(3)

In [ ]:
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

In [ ]:
titanic_df['Age_by_10']=titanic_df['Age_by_10']+100
titanic_df.head(3)

## DataFrame 데이터 삭제

In [ ]:
titanic_drop_df=titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)

In [ ]:
titanic_df.head(3)

In [ ]:
drop_result=titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=True)
print('inplace=True로 drop 후 반환된 값:',drop_result)
titanic_df.head(3)

In [ ]:
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2],axis=0,inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

## Index 객체

In [ ]:
# 원본 파일 다시 로딩
titanic_df=pd.read_csv('titanic_train.csv')
# Index 객체 추출
indexes=titanic_df.index
# Index 객체를 실제 값 array로 변환
print('Index 객체 array값:\n',indexes.values)

In [ ]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

In [ ]:
indexes[0]=5

In [ ]:
series_fair=titanic_df['Fare']
print('Fair Series max 값:',series_fair.max())
print('Fair Series sum 값:',series_fair.sum())
print('sum() Fair Series:',sum(series_fair))
print('Fair Series + 3:\n',(series_fair + 3).head(3))

In [ ]:
titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

In [ ]:
print('### before reset_index ###')
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:',type(value_counts))
new_value_counts=value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:',type(new_value_counts))

## 데이터 셀렉션 및 필터링

In [ ]:
print('단일 칼럼 데이터 추출:\n',titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n',titanic_df[['Survived','Pclass']].head(3))
print('[] 안에 숫자 index는 KeyError 오류 발생:\n',titanic_df[0])

In [ ]:
titanic_df[0:2]

In [ ]:
titanic_df[titanic_df['Pclass']==3].head(3)

In [ ]:
data={'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],
      'Year':[2011,2016,2015,2015],
      'Gender':['Male','Female','Male','Male']}
data_df=pd.DataFrame(data,index['one','two','three','four'])
data_df

In [ ]:
# 아래 코드는 오류를 발생시킴
data_df.iloc[0,'Name']

In [ ]:
# 아래 코드는 오류를 발생시킴
data_df.iloc['one',0]

In [ ]:
print("\n 맨 마지막 칼럼 데이터 [:,-1] \n",data_df.iloc[:,-1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:,:-1] \n",data_df.iloc[:,:-1])

In [ ]:
data_df.loc['one','Name']

In [ ]:
# 다음 코드는 오류를 발생시킴
data_df.loc[0,'Name']

In [ ]:
print('위치기반 iloc slicing\n',data_df.iloc[0:1,0],'\n')
print('위치기반 iloc slicing\n',data_df.loc['one':'two','Name'])

In [ ]:
titanic_df=pd.read_csv('titanic_train.csv')
titanic_boolean=titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

In [ ]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

In [ ]:
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

In [ ]:
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

In [ ]:
cond1=titanic_df['Age']>60
cond2=titanic_df['Pclass']==1
cond3=titanic_df['Sex']=='female'
titanic_df[cond1&cond2&cond3]

## 정렬, Aggregation 함수, GroupBy 적용

In [ ]:
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

In [ ]:
titanic_sorted=titanic_df.sort_values(by=['Pclass','Name'],ascending=False)
titanic_sorted.head(3)

In [ ]:
titanic_df.count()

In [ ]:
titanic_df[['Age','Fare']].mean()

In [ ]:
titanic_groupby=titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

In [ ]:
titanic_groupby=titanic_df.groupby('Pclass').count()
titanic_groupby

In [ ]:
titanic_groupby=titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

In [ ]:
titanic_groupby('Pclass')['Age'].agg([max,min])

In [ ]:
agg_format={'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

## 결손 데이터 처리하기

In [ ]:
titanic_df.isna().head(3)

In [ ]:
titanic_df.isna().sum()

In [ ]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

In [ ]:
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

## apply lambda 식으로 데이터 가공

In [ ]:
def get_square(a): return a**2
print('3의 제곱은:',get_square(3))

In [ ]:
lambda_square=lambda x:x**2
print('3의 제곱은:',lambda_square(3))

In [ ]:
a=[1,2,3]
squares=map(lambda x:x**2,a)
list(squares)

In [ ]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x:len(x))
titanic_df[['Name','Name_len']].head(3)

In [ ]:
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x:'Child' if x <= 15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

In [ ]:
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x:'Child' if x<=15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

In [ ]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age):
  cat=''
  if age<=5:cat='Baby'
  elif age<=12:cat='Chile'
  elif age<=18:cat='Teenager'
  elif age<=25:cat='Student'
  elif age<=35:cat='Young Adult'
  elif age<=60:cat='Adult'
  else:cat='Elderly'

  return cat

# lambda 식에 위에서 생성한 get_category() 함수를 반환값으로 지정
# get_category(x)는 입력값으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x:get_category(x))
titanic_df[['Age','Age_cat']].head()